run:
  timeout: "5m"

linters:
  disable-all: true
  enable: [
    "goimports",
    "gofmt",
  ]

linters-settings:
  goimports:
    local-prefixes: github.com/nitrictech
  govet:
    check-shadowing: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
