name: Release Docker images
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # Setup docker build image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Login to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Sets the latest tag to rc-latest if release was a prerelease
      - name: Set latest tag RC
        if: "github.event.release.prerelease"
        run: |
          echo "latest_tag=rc-latest" >> $GITHUB_ENV

      # Uses latest tag if release was a production release
      - name: Set latest tag Prod
        if: "!github.event.release.prerelease"
        run: |
          echo "latest_tag=latest" >> $GITHUB_ENV

      # Push development image
      - name: Push Local Static image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pkg/providers/dev/dev.dockerfile
          push: true
          tags: |
            nitricimages/membrane-local:${{ env.latest_tag }}
            nitricimages/membrane-local:${{ github.event.release.tag_name }}
      # Push AWS image
      - name: Push AWS Static image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pkg/providers/aws/aws.dockerfile
          push: true
          tags: |
            nitricimages/membrane-aws:${{ env.latest_tag }}
            nitricimages/membrane-aws:${{ github.event.release.tag_name }}
      # Push GCP image
      - name: Push GCP Static image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pkg/providers/gcp/gcp.dockerfile
          push: true
          tags: |
            nitricimages/membrane-gcp:${{ env.latest_tag }}
            nitricimages/membrane-gcp:${{ github.event.release.tag_name }}
      # Push Azure image
      - name: Push Azure Static image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pkg/providers/azure/azure.dockerfile
          push: true
          tags: |
            nitricimages/membrane-azure:${{ env.latest_tag }}
            nitricimages/membrane-azure:${{ github.event.release.tag_name }}
      # Push Digital Ocean image
      - name: Push Digital Ocean image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pkg/providers/do/do.dockerfile
          push: true
          tags: |
            nitricimages/membrane-do:${{ env.latest_tag }}
            nitricimages/membrane-do:${{ github.event.release.tag_name }}
