name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.GOLANG_TOKEN}}
        submodules: recursive
    - name: Setup Go
      uses: actions/setup-go@v2-beta      
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - name: Install modules
      run: make install-tools
    - name: Check Source License Headers
      run: make license-header-check
    - name: Run Tests
      run: make test
    - name: Check Dependency Licenses
      run: make license-check