name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - name: Linting check
      run: make lint
    - name: Generate Sources
      run: make generate-sources
    - name: Check generated sources
      run: |
        git add .
        git diff --cached --quiet
    - name: Run Tests
      run: make test-coverage       
    - name: Check Dependency Licenses
      run: make license-check
    # Upload coverage report if main is set
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./core/all.coverprofile,./provider/aws/all.coverprofile,./provider/gcp/all.coverprofile,./provider/azure/all.coverprofile # optional
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
  
  # Run integration tests
  test-integration:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - name: Run Integration Tests
      run: make test-integration